sudo: false

language: generic

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=g++-4.9 CXX=g++-4.9 GCOV=gcov-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - python-pip

before_install:
    - pip install --user urllib3[secure]
    - pip install --user cpp-coveralls

script:
    - ./bootstrap
    - cd build
    - cmake --version
    - cmake -DCMAKE_BUILD_TYPE=Coverage ..
    - make VERBOSE=1
    - make check
    - g++-4.9 --version
    - gcov-4.9 --version
    - which gcov-4.9
    - which gcov

after_success:
    - coveralls --gcov /usr/bin/gcov-4.9 --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
    email: false

