sudo: required
dist: trusty

language: cpp
compiler:
    - g++

install:
    # get c++11 support
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
        - gcc-4.8
        - g++-4.8
        - cmake
        - cmake-data

before_script:
    # setup environment
    - sudo -H sh ./script/packages.sh

script:
    # bootstrap
    - ./bootstrap
    - cd build
    - cmake --version
    - cmake -DCMAKE_BUILD_TYPE=RELEASE ..
    - make
    - make check
