sudo: false

language: cpp

addons:
  apt:
    sources:
	- ubuntu-toolchain-r-test

before_install:
	- pip install --user cpp-coveralls

script:
    - ./bootstrap
    - cd build
    - cmake --version
    - cmake -DCMAKE_BUILD_TYPE=RELEASE ..
    - make
    - make check

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
email: false

