sudo: false

language: generic

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=g++-4.8 CXX=g++-4.8 GCOV=gcov-4.8

    - os: linux
      compiler: gcc
      env: COMPILER=g++-5 CXX=g++-5 GCOV=gcov-5

    - os: linux
      env: COMPILER=clang++-3.6 CXX=clang++-3.6

    - os: linux
      env: COMPILER=clang++-3.8 CXX=clang++-3.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.8
    packages:
      - g++-4.8
      - g++-5
      - clang-3.6
      - clang-3.8
      - python-pip

before_install:
    - pip install --user urllib3[secure]
    - pip install --user cpp-coveralls

script:
    - ./bootstrap
    - cd build
    - cmake --version
    - cmake -DCMAKE_BUILD_TYPE=RELEASE ..
    - make
    - make check

after_success:
    - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
    email: false

